<?php
namespace TT\Modules\DemoData\Generators;

if ( ! defined( 'ABSPATH' ) ) exit;

use TT\Infrastructure\Tenancy\CurrentClub;
use TT\Modules\DemoData\DemoBatchRegistry;
use TT\Modules\Training\Repositories\TrainingPlansRepository;

/**
 * TrainingPlanGenerator — writes tt_training_plans, tt_training_plan_blocks
 * and the derived tt_training_plan_principles.
 *
 * #2498 inherited this: wave 3 classified those three tables as `planned`
 * against this issue rather than exempting them, on the grounds that a
 * demo academy with an empty training history tells the module's story
 * badly. A coach evaluating TalentTrack should open Training and find
 * plans that look like a season, not an empty list with a New button.
 *
 * ## Why these plans are not generated by the real composer
 *
 * `TrainingPlanComposer` refuses any age group without a VCT age profile,
 * and only U10 to U14 are seeded (#2601). A demo academy fielding U8s
 * would get nothing at all. Demo data also has to be reproducible from a
 * seed, and the composer reads recent-picks history that the demo batch
 * itself is in the middle of writing.
 *
 * So this writes plausible plans directly, the same way every other demo
 * generator writes its own rows. The shape is what matters — a themed
 * plan per team per fortnight, warm-up through cool-down, drawn from
 * whatever the library actually holds.
 */
class TrainingPlanGenerator implements DependentGeneratorInterface {

    /**
     * The plan skeleton. Six blocks that read like a real evening, with
     * the durations a 75-minute session actually divides into.
     *
     * @var list<array{type:string, minutes:int}>
     */
    private const SHAPE = [
        [ 'type' => 'warmup',   'minutes' => 12 ],
        [ 'type' => 'rondo',    'minutes' => 10 ],
        [ 'type' => 'main',     'minutes' => 22 ],
        [ 'type' => 'game',     'minutes' => 20 ],
        [ 'type' => 'cooldown', 'minutes' => 6 ],
        [ 'type' => 'talk',     'minutes' => 5 ],
    ];

    /** @var array<string, array<string,string>> */
    private const COPY_BY_LANGUAGE = [
        'en_US' => [
            'build_up'   => 'Building up from the back',
            'pressing'   => 'Pressing as a unit',
            'finishing'  => 'Finishing in the box',
            'possession' => 'Keeping the ball under pressure',
            'points'     => 'Name the moment out loud, not afterwards. Everyone plays their own position.',
            'talk'       => 'Close out: what went well, one thing for Saturday.',
        ],
        'nl_NL' => [
            'build_up'   => 'Opbouwen van achteruit',
            'pressing'   => 'Samen storen',
            'finishing'  => 'Afronden in de zestien',
            'possession' => 'Balbezit onder druk',
            'points'     => 'Benoem het moment hardop, niet achteraf. Iedereen speelt zijn eigen positie.',
            'talk'       => 'Afsluiten: wat ging goed, en één punt voor zaterdag.',
        ],
    ];

    /** The themes a demo season cycles through. */
    private const THEMES = [ 'build_up', 'pressing', 'finishing', 'possession' ];

    private DemoBatchRegistry $registry;

    /** @var object[] */
    private array $teams;

    /** @var array<string,int> */
    private array $users;

    private int $weeks;

    private string $language;

    public static function category(): string {
        return 'training_plans';
    }

    public static function fromContext( GeneratorContext $ctx ): self {
        return new self( $ctx->registry, $ctx->teams, $ctx->users, $ctx->weeks(), $ctx->contentLanguage );
    }

    /**
     * @param object[]          $teams
     * @param array<string,int> $users
     */
    public function __construct( DemoBatchRegistry $registry, array $teams, array $users, int $weeks, string $language = '' ) {
        $this->registry = $registry;
        $this->teams    = $teams;
        $this->users    = $users;
        $this->weeks    = max( 1, $weeks );
        $this->language = $language !== '' ? $language : ( function_exists( 'get_locale' ) ? (string) get_locale() : 'en_US' );
    }

    public function generate(): int {
        global $wpdb;

        $copy      = self::COPY_BY_LANGUAGE[ self::resolveLanguage( $this->language ) ];
        $author    = (int) ( $this->users['hjo'] ?? $this->users['admin'] ?? 0 );
        $exercises = $this->exercisesByType();

        $total = 0;
        foreach ( $this->teams as $team_index => $team ) {
            $team_id = (int) ( $team->id ?? 0 );
            if ( $team_id <= 0 ) continue;

            // One plan a fortnight, so a season's worth of training reads
            // as a rhythm rather than a wall of rows.
            $count = max( 1, (int) floor( $this->weeks / 2 ) );
            for ( $i = 0; $i < $count; $i++ ) {
                $theme = self::THEMES[ ( $team_index + $i ) % count( self::THEMES ) ];
                $when  = strtotime( '-' . ( ( $count - $i ) * 2 ) . ' weeks' );
                if ( $when === false ) $when = time();

                $plan_id = $this->writePlan( $team, $theme, $copy, $author, $when );
                if ( $plan_id <= 0 ) continue;

                $this->writeBlocks( $plan_id, $exercises, $copy );

                // The derived principle rows are the module's payoff — a
                // plan that covers nothing is invisible to the coverage
                // panel and the exposure report. Rebuild them the same
                // way a real save would.
                ( new TrainingPlansRepository() )->syncDerivedPrinciples( $plan_id );

                // Three tags, all carrying the PLAN id.
                //
                // The blocks and derived principle rows are wiped through
                // `TABLE_QUIRKS[…]['delete_by']`, which deletes by
                // `plan_id` — but the cleaner reads the tag set for the
                // child type FIRST and skips the table entirely when it
                // is empty. So the child types need a tag even though
                // they are addressed by their parent's id, exactly as
                // `tt_player_parents` is. One tag per plan, not one per
                // block: six times the registry rows would buy nothing.
                $this->registry->tag( 'training_plan', $plan_id, [ 'team_id' => $team_id ] );
                $this->registry->tag( 'training_plan_block', $plan_id, [ 'team_id' => $team_id ] );
                $this->registry->tag( 'training_plan_principle', $plan_id, [ 'team_id' => $team_id ] );
                $total++;
            }
        }

        return $total;
    }

    /**
     * @param array<string,string> $copy
     */
    private function writePlan( object $team, string $theme, array $copy, int $author, int $when ): int {
        global $wpdb;

        $minutes = 0;
        foreach ( self::SHAPE as $slot ) $minutes += $slot['minutes'];

        $wpdb->insert( "{$wpdb->prefix}tt_training_plans", [
            'club_id'                => CurrentClub::id(),
            'uuid'                   => self::uuid(),
            'title'                  => sprintf(
                '%s · %s',
                $copy[ $theme ] ?? $theme,
                gmdate( 'd-m-Y', $when )
            ),
            'team_id'                => (int) $team->id,
            'age_group_key'          => isset( $team->age_group ) ? (string) $team->age_group : null,
            'theme_key'              => $theme,
            'total_duration_minutes' => $minutes,
            'is_template'            => 0,
            'visibility'             => 'club',
            'source'                 => 'manual',
            'author_user_id'         => (int) ( $team->head_coach_user_id ?? $author ),
            'created_at'             => gmdate( 'Y-m-d H:i:s', $when ),
            'updated_at'             => gmdate( 'Y-m-d H:i:s', $when ),
        ] );

        return (int) $wpdb->insert_id;
    }

    /**
     * @param array<string, list<int>> $exercises
     * @param array<string,string>     $copy
     */
    private function writeBlocks( int $plan_id, array $exercises, array $copy ): void {
        global $wpdb;

        foreach ( self::SHAPE as $order => $slot ) {
            $pool        = $exercises[ $slot['type'] ] ?? $exercises['any'] ?? [];
            $exercise_id = $pool !== [] ? $pool[ $plan_id % count( $pool ) ] : null;

            // A team talk has no drill behind it, which is exactly the
            // free-text case the blocks table was built to hold.
            if ( $slot['type'] === 'talk' ) $exercise_id = null;

            $wpdb->insert( "{$wpdb->prefix}tt_training_plan_blocks", [
                'club_id'          => CurrentClub::id(),
                'uuid'             => self::uuid(),
                'plan_id'          => $plan_id,
                'order_index'      => $order,
                'block_type'       => $slot['type'],
                'exercise_id'      => $exercise_id,
                'title_override'   => $slot['type'] === 'talk' ? $copy['talk'] : null,
                'coaching_points'  => $slot['type'] === 'main' ? $copy['points'] : null,
                'duration_minutes' => $slot['minutes'],
            ] );
        }
    }

    /**
     * Group the library by the block type each exercise best fits, so a
     * warm-up slot gets a warm-up rather than an 11v11.
     *
     * Falls back to `any` when the library carries no theme hints, which
     * is the state a fresh install without the VCT catalogue is in.
     *
     * @return array<string, list<int>>
     */
    private function exercisesByType(): array {
        global $wpdb;

        $rows = $wpdb->get_results( $wpdb->prepare(
            "SELECT id, tactical_theme, intensity_band
               FROM {$wpdb->prefix}tt_exercises
              WHERE club_id = %d AND archived_at IS NULL AND superseded_by_id IS NULL
              ORDER BY id ASC",
            CurrentClub::id()
        ) );

        $out = [ 'any' => [] ];
        foreach ( (array) $rows as $row ) {
            $id           = (int) $row->id;
            $out['any'][] = $id;

            $band = (int) ( $row->intensity_band ?? 0 );
            if ( $band > 0 && $band <= 3 ) {
                $out['warmup'][]   = $id;
                $out['cooldown'][] = $id;
            } elseif ( $band >= 7 ) {
                $out['game'][] = $id;
            } else {
                $out['main'][]  = $id;
                $out['rondo'][] = $id;
            }
        }

        return $out;
    }

    private static function uuid(): string {
        return function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),
            mt_rand( 0, 0x0fff ) | 0x4000, mt_rand( 0, 0x3fff ) | 0x8000,
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
        );
    }

    private static function resolveLanguage( string $locale ): string {
        if ( isset( self::COPY_BY_LANGUAGE[ $locale ] ) ) return $locale;
        $prefix = substr( $locale, 0, 2 );
        foreach ( array_keys( self::COPY_BY_LANGUAGE ) as $key ) {
            if ( strpos( $key, $prefix ) === 0 ) return $key;
        }
        return 'en_US';
    }
}
