<?php
/**
 * Write routes that predate the args rule (#3689). Read by
 * `tools/check-rest-args.php`.
 *
 * Each line is `file | route path | methods`. The gate fails when a line
 * here no longer violates: when you give one of these routes its `args`,
 * delete its line in the same PR so the list only gets shorter. Never add a
 * line to make a new route pass; declare the route's args instead.
 */

return [
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<activity_id>\\d+)/contributions | PUT',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<activity_id>\\d+)/result | PUT',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/evaluation-skipped | PATCH',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/guests | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/ratings/bulk | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/status | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /attendance/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/ActivitiesRestController.php | /attendance/bulk | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /minutes/bulk | POST',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises | POST',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises/replace | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/(?P<id>[A-Za-z0-9._-]+)/restore | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/commit | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/dry-run | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/preview | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/run | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/settings | POST',
    'src/Infrastructure/REST/ConfigRestController.php | /config | POST',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields | POST',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories | POST',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/EvalCoverageRestController.php | /eval-coverage/windows | PUT',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations | POST',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercise-scenes/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercise-scenes/(?P<id>\\d+)/primary | POST',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercises/(?P<id>\\d+)/scenes | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/(?P<id>\\d+)/promote | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/import | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/principles/bulk | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/assignments | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/assignments/(?P<assignment_id>\\d+) | PUT',
    'src/Infrastructure/REST/GoalsRestController.php | /goals | POST',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/status | PATCH',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/InvitationsRestController.php | /invitations | POST',
    'src/Infrastructure/REST/LookupsRestController.php | /translations/preview | POST',
    'src/Infrastructure/REST/MeasurementsRestController.php | /measurements/definitions | POST',
    'src/Infrastructure/REST/MeasurementsRestController.php | /measurements/definitions/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/MeasurementsRestController.php | /measurements/results/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/MeasurementsRestController.php | /measurements/sessions | POST',
    'src/Infrastructure/REST/MeasurementsRestController.php | /players/(?P<player_id>\\d+)/measurements | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media/(?P<uuid>[a-f0-9-]{36}) | PATCH',
    'src/Infrastructure/REST/MediaRestController.php | /media/(?P<uuid>[a-f0-9-]{36})/links | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media/retention/(?P<link_id>\\d+) | POST',
    'src/Infrastructure/REST/MinutesGridPreferencesRestController.php | /me/preferences/minutes-grid | PUT',
    'src/Infrastructure/REST/OnboardingRestController.php | \'/onboarding/\' . $path | POST',
    'src/Infrastructure/REST/PeopleRestController.php | /people | POST',
    'src/Infrastructure/REST/PeopleRestController.php | /people/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PeopleRestController.php | /people/delete-preview | POST',
    'src/Infrastructure/REST/PlayerAccountRestController.php | /players/(?P<id>\\d+)/account | POST',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /player-events/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /player-injuries/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /players/(?P<id>\\d+)/events | POST',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /players/(?P<id>\\d+)/injuries | POST',
    'src/Infrastructure/REST/PlayerStatusRestController.php | /players/(?P<id>\\d+)/behaviour-ratings | POST',
    'src/Infrastructure/REST/PlayerStatusRestController.php | /players/(?P<id>\\d+)/potential | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PlayersRestController.php | /players/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/import | POST',
    'src/Infrastructure/REST/SavedViewsRestController.php | $base . \'/(?P<id>\\d+)\' | PATCH',
    'src/Infrastructure/REST/SavedViewsRestController.php | $base | POST',
    'src/Infrastructure/REST/SeasonRolloverRestController.php | /season-rollover/execute | POST',
    'src/Infrastructure/REST/SeasonRolloverRestController.php | /season-rollover/plan | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/base-url | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/credentials | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/test | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/credentials | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/preview | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/sync | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/test | POST',
    'src/Infrastructure/REST/StravaRestController.php | /players/(?P<id>\\d+)/strava/connect | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/app | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/webhook | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/webhook/subscription | POST',
    'src/Infrastructure/REST/TeamDetailPreferencesRestController.php | /me/preferences/team-detail | PUT',
    'src/Infrastructure/REST/TeamsRestController.php | /teams | POST',
    'src/Infrastructure/REST/TeamsRestController.php | /teams/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/TeamsRestController.php | /teams/(?P<id>\\d+)/players/(?P<player_id>\\d+) | POST',
    'src/Infrastructure/REST/TeamsRestController.php | /teams/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+) | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/assignments | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/auto-plan | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/complete | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/kickoff | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/squad | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/squad/(?P<player_id>\\d+) | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/blocks | PUT',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/duplicate | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/publish | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/generate | POST',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs | POST',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+)/blocks/(?P<block>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+)/observations | POST',
    'src/Infrastructure/REST/TranslationsRestController.php | /translations/clear-cache | POST',
    'src/Infrastructure/REST/TranslationsRestController.php | /translations/settings | POST',
    'src/Infrastructure/REST/VisionExtractRestController.php | /vision/extract | POST',
    'src/Modules/AdminCenterClient/BroadcastsRestController.php | /me/broadcasts/(?P<id>\\d+)/dismiss | POST',
    'src/Modules/Alerts/Rest/AlertsRestController.php | /alerts/(?P<uuid>[a-f0-9\\-]{36})/dismiss | POST',
    'src/Modules/Alerts/Rest/AlertsRestController.php | /alerts/(?P<uuid>[a-f0-9\\-]{36})/read | POST',
    'src/Modules/Alerts/Rest/AlertsRestController.php | /alerts/evaluate | POST',
    'src/Modules/Alerts/Rest/AlertsRestController.php | /alerts/policy | PUT',
    'src/Modules/Alerts/Rest/AlertsRestController.php | /alerts/preferences | PUT',
    'src/Modules/Authorization/Rest/MatrixRestController.php | /authorization/matrix/reset | POST',
    'src/Modules/CustomWidgets/Rest/CustomWidgetsRestController.php | /custom-widgets | POST',
    'src/Modules/CustomWidgets/Rest/CustomWidgetsRestController.php | /custom-widgets/(?P<id>[A-Za-z0-9_-]+) | PUT',
    'src/Modules/CustomWidgets/Rest/CustomWidgetsRestController.php | /custom-widgets/(?P<id>[A-Za-z0-9_-]+)/clear-cache | POST',
    'src/Modules/DemoData/Rest/DemoRunRestController.php | /demo-runs/discard | POST',
    'src/Modules/DemoData/Rest/DemoRunRestController.php | /demo-runs/step | POST',
    'src/Modules/Export/Rest/ExportRestController.php | /exports/(?P<key>[a-z0-9_-]+) | GET,POST',
    'src/Modules/Holidays/Rest/HolidaysRestController.php | /holidays | POST',
    'src/Modules/Holidays/Rest/HolidaysRestController.php | /holidays/(?P<id>\\d+)/restore | POST',
    'src/Modules/Holidays/Rest/HolidaysRestController.php | /holidays/(?P<id>\\d+)/trash | POST',
    'src/Modules/Knowledge/Rest/KnowledgeRestController.php | /courses/(?P<slug>[a-z0-9-]+)/enrolments | POST',
    'src/Modules/Knowledge/Rest/KnowledgeRestController.php | /courses/(?P<slug>[a-z0-9-]+)/quiz/(?P<lesson>[a-z0-9-]+) | POST',
    'src/Modules/Knowledge/Rest/KnowledgeRestController.php | /courses/(?P<slug>[a-z0-9-]+)/submissions/(?P<lesson>[a-z0-9-]+) | POST',
    'src/Modules/Knowledge/Rest/KnowledgeRestController.php | /submissions/(?P<id>\\d+) | PATCH',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis | PUT',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/players/(?P<player_id>\\d+) | PUT',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/sections/(?P<section_key>[a-z_]+) | PUT',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/share | POST',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/share/rotate | POST',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/\' . $action | ?',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/goal-event/(?P<event_uuid>[a-f0-9-]+)\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/minutes\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/substitution/(?P<event_uuid>[a-f0-9-]+)\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/tracked-event\' | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<activity_id>\\d+)/share | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<activity_id>\\d+)/share/rotate | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<prep_id>\\d+)/role | PUT',
    'src/Modules/Measurements/Rest/MeasurementDefinitionsRestController.php | /measurement-definitions | POST',
    'src/Modules/Measurements/Rest/MeasurementDefinitionsRestController.php | /measurement-definitions/(?P<id>\\d+) | PUT',
    'src/Modules/Measurements/Rest/MeasurementDefinitionsRestController.php | /measurement-definitions/(?P<id>\\d+)/levels | POST',
    'src/Modules/Measurements/Rest/MeasurementDefinitionsRestController.php | /measurement-definitions/(?P<id>\\d+)/targets | POST',
    'src/Modules/Methodology/Rest/AbstractMethodologyRestController.php | \'/\' . $base . \'/(?P<id>\\d+)\' | PUT',
    'src/Modules/Methodology/Rest/AbstractMethodologyRestController.php | \'/\' . $base | POST',
    'src/Modules/Methodology/Rest/FormationsRestController.php | \'/\' . $base . \'/(?P<id>\\d+)/positions\' | POST',
    'src/Modules/Methodology/Rest/FormationsRestController.php | \'/\' . $base . \'/(?P<id>\\d+)/positions/(?P<pid>\\d+)\' | PUT',
    'src/Modules/Methodology/Rest/FrameworkPrimerRestController.php | \'/\' . $base . \'/(?P<id>\\d+)\' | PUT',
    'src/Modules/Methodology/Rest/MethodologySetsRestController.php | \'/\' . static::restBase() . \'/(?P<id>\\d+)/default\' | PUT',
    'src/Modules/Methodology/Rest/VisionRestController.php | \'/\' . $base . \'/(?P<id>\\d+)\' | PUT',
    'src/Modules/Pdp/Rest/PdpBlocksRestController.php | /pdp-blocks | PUT',
    'src/Modules/Pdp/Rest/PdpConversationsRestController.php | /pdp-conversations/(?P<id>\\d+) | PATCH',
    'src/Modules/Pdp/Rest/PdpFilesRestController.php | /pdp-files | POST',
    'src/Modules/Pdp/Rest/PdpFilesRestController.php | /pdp-files/(?P<id>\\d+) | PATCH',
    'src/Modules/Pdp/Rest/PdpFilesRestController.php | /pdp-files/(?P<id>\\d+)/permanent-delete | POST',
    'src/Modules/Pdp/Rest/PdpFilesRestController.php | /pdp-files/(?P<id>\\d+)/restore | POST',
    'src/Modules/Pdp/Rest/PdpPrepRestController.php | /pdp-conversations/(?P<id>\\d+)/prep | PUT,PATCH',
    'src/Modules/Pdp/Rest/PdpPrepRestController.php | /pdp-prep-questions | POST',
    'src/Modules/Pdp/Rest/PdpPrepRestController.php | /pdp-prep-questions/(?P<id>\\d+) | PUT,PATCH',
    'src/Modules/Pdp/Rest/PdpPrepRestController.php | /pdp-prep-questions/order | PUT',
    'src/Modules/Pdp/Rest/PdpVerdictsRestController.php | /pdp-files/(?P<id>\\d+)/verdict | PUT',
    'src/Modules/Pdp/Rest/SeasonsRestController.php | /seasons | POST',
    'src/Modules/Pdp/Rest/SeasonsRestController.php | /seasons/(?P<id>\\d+) | PATCH',
    'src/Modules/Pdp/Rest/SeasonsRestController.php | /seasons/(?P<id>\\d+)/current | PATCH',
    'src/Modules/Prospects/Rest/ProspectsRestController.php | /prospects/(?P<id>\\d+) | PATCH',
    'src/Modules/Prospects/Rest/ProspectsRestController.php | /prospects/log | POST',
    'src/Modules/Prospects/Rest/TestTrainingsRestController.php | /test-trainings | POST',
    'src/Modules/Push/Rest/PushSubscriptionsRestController.php | /push-subscriptions | POST',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff-certifications/(?P<id>\\d+) | PUT',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff-evaluations/(?P<id>\\d+) | PUT',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff-goals/(?P<id>\\d+) | PUT',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff/(?P<person_id>\\d+)/certifications | POST',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff/(?P<person_id>\\d+)/evaluations | POST',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff/(?P<person_id>\\d+)/goals | POST',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff/(?P<person_id>\\d+)/mentorships | POST',
    'src/Modules/StaffDevelopment/Rest/StaffDevelopmentRestController.php | /staff/(?P<person_id>\\d+)/pdp | PUT',
    'src/Modules/TeamDevelopment/Rest/PlayerAttributesRestController.php | /chemistry/config | PUT',
    'src/Modules/TeamDevelopment/Rest/PlayerAttributesRestController.php | /chemistry/position-matrix | PUT',
    'src/Modules/TeamDevelopment/Rest/PlayerAttributesRestController.php | /players/(?P<player_id>\\d+)/attributes | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /blueprints/(?P<id>\\d+) | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /blueprints/(?P<id>\\d+)/assignment | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /blueprints/(?P<id>\\d+)/assignments | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /blueprints/(?P<id>\\d+)/clone | POST',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /blueprints/(?P<id>\\d+)/status | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /teams/(?P<id>\\d+)/blueprints | POST',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /teams/(?P<id>\\d+)/chemistry/preview | POST',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /teams/(?P<id>\\d+)/formation | PUT',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /teams/(?P<id>\\d+)/pairings | POST',
    'src/Modules/TeamDevelopment/Rest/TeamDevelopmentRestController.php | /teams/(?P<id>\\d+)/style | PUT',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases | POST',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases/(?P<id>\\d+) | PUT',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases/(?P<id>\\d+)/extend | POST',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases/(?P<id>\\d+)/inputs/release | POST',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases/(?P<id>\\d+)/letters | POST',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-cases/(?P<id>\\d+)/staff | POST',
    'src/Modules/Trials/Rest/TrialsRestController.php | /trial-reminders/run | POST',
    'src/Modules/Vct/Rest/VctAgeProfilesRestController.php | /vct/age-profiles | POST',
    'src/Modules/Vct/Rest/VctAgeProfilesRestController.php | /vct/age-profiles/(?P<id>\\d+) | PATCH',
    'src/Modules/Vct/Rest/VctCycleWeeksRestController.php | /vct/cycle-weeks | PUT',
    'src/Modules/Vct/Rest/VctExercisesRestController.php | /vct/exercises | POST',
    'src/Modules/Vct/Rest/VctExercisesRestController.php | /vct/exercises/(?P<id>\\d+) | PATCH',
    'src/Modules/Vct/Rest/VctMacroBlocksRestController.php | /vct/macro-blocks | PUT',
    'src/Modules/Vct/Rest/VctPhvFlagsRestController.php | /vct/players/(?P<id>\\d+)/phv-flag | PATCH',
    'src/Modules/Vct/Rest/VctTeamCyclesRestController.php | /vct/team-cycles | PUT',
    'src/Modules/Vct/Rest/VctTeamSchedulesRestController.php | /vct/teams/(?P<team_id>\\d+)/schedule | PUT',
    'src/Modules/Vct/Rest/VctTrainingsRestController.php | /vct/sessions/(?P<id>\\d+) | PATCH',
    'src/Modules/Vct/Rest/VctTrainingsRestController.php | /vct/sessions/(?P<id>\\d+)/publish | POST',
    'src/Modules/Vct/Rest/VctTrainingsRestController.php | /vct/sessions/generate | POST',
    'src/Modules/Wizards/Evaluation/EvaluationRowRestController.php | /wizards/new-evaluation/insert-row | POST',
];
