<?php
/**
 * Write routes that predate the args rule (#3689). Read by
 * `tools/check-rest-args.php`.
 *
 * Each line is `file | route path | methods`. The gate fails when a line
 * here no longer violates: when you give one of these routes its `args`,
 * delete its line in the same PR so the list only gets shorter. Never add a
 * line to make a new route pass; declare the route's args instead.
 */

return [
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<activity_id>\\d+)/contributions | PUT',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<activity_id>\\d+)/result | PUT',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/evaluation-skipped | PATCH',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/guests | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/ratings/bulk | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /activities/(?P<id>\\d+)/status | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /attendance/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/ActivitiesRestController.php | /attendance/bulk | POST',
    'src/Infrastructure/REST/ActivitiesRestController.php | /minutes/bulk | POST',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises | POST',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ActivityExercisesRestController.php | /activities/(?P<activity_id>\\d+)/exercises/replace | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/(?P<id>[A-Za-z0-9._-]+)/restore | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/commit | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/dry-run | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/migration/preview | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/run | POST',
    'src/Infrastructure/REST/BackupRestController.php | /backups/settings | POST',
    'src/Infrastructure/REST/ConfigRestController.php | /config | POST',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields | POST',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/CustomFieldsRestController.php | /custom-fields/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories | POST',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/EvalCategoriesRestController.php | /eval-categories/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/EvalCoverageRestController.php | /eval-coverage/windows | PUT',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/EvaluationsRestController.php | /evaluations/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercise-scenes/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercise-scenes/(?P<id>\\d+)/primary | POST',
    'src/Infrastructure/REST/ExerciseScenesRestController.php | /exercises/(?P<id>\\d+)/scenes | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/(?P<id>\\d+)/promote | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/import | POST',
    'src/Infrastructure/REST/ExercisesRestController.php | /exercises/principles/bulk | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/(?P<id>\\d+)/move | POST',
    'src/Infrastructure/REST/FunctionalRolesRestController.php | /functional-roles/assignments/(?P<assignment_id>\\d+) | PUT',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/status | PATCH',
    'src/Infrastructure/REST/GoalsRestController.php | /goals/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/InvitationsRestController.php | /invitations | POST',
    'src/Infrastructure/REST/LookupsRestController.php | /translations/preview | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media/(?P<uuid>[a-f0-9-]{36}) | PATCH',
    'src/Infrastructure/REST/MediaRestController.php | /media/(?P<uuid>[a-f0-9-]{36})/links | POST',
    'src/Infrastructure/REST/MediaRestController.php | /media/retention/(?P<link_id>\\d+) | POST',
    'src/Infrastructure/REST/OnboardingRestController.php | \'/onboarding/\' . $path | POST',
    'src/Infrastructure/REST/PeopleRestController.php | /people/delete-preview | POST',
    'src/Infrastructure/REST/PlayerAccountRestController.php | /players/(?P<id>\\d+)/account | POST',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /player-events/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /player-injuries/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /players/(?P<id>\\d+)/events | POST',
    'src/Infrastructure/REST/PlayerJourneyRestController.php | /players/(?P<id>\\d+)/injuries | POST',
    'src/Infrastructure/REST/PlayerStatusRestController.php | /players/(?P<id>\\d+)/behaviour-ratings | POST',
    'src/Infrastructure/REST/PlayerStatusRestController.php | /players/(?P<id>\\d+)/potential | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/PlayersRestController.php | /players/import | POST',
    'src/Infrastructure/REST/SavedViewsRestController.php | $base . \'/(?P<id>\\d+)\' | PATCH',
    'src/Infrastructure/REST/SavedViewsRestController.php | $base | POST',
    'src/Infrastructure/REST/SeasonRolloverRestController.php | /season-rollover/execute | POST',
    'src/Infrastructure/REST/SeasonRolloverRestController.php | /season-rollover/plan | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/base-url | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/credentials | POST',
    'src/Infrastructure/REST/SpondRestController.php | /spond/test | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/credentials | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/preview | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/sync | POST',
    'src/Infrastructure/REST/SpondRestController.php | /teams/(?P<id>\\d+)/spond/test | POST',
    'src/Infrastructure/REST/StravaRestController.php | /players/(?P<id>\\d+)/strava/connect | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/app | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/webhook | POST',
    'src/Infrastructure/REST/StravaRestController.php | /strava/webhook/subscription | POST',
    'src/Infrastructure/REST/TeamsRestController.php | /teams/(?P<id>\\d+)/players/(?P<player_id>\\d+) | POST',
    'src/Infrastructure/REST/TeamsRestController.php | /teams/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+) | PUT',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+) | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/assignments | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/auto-plan | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/complete | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/matches/(?P<match_id>\\d+)/kickoff | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/restore | POST',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/squad | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/squad/(?P<player_id>\\d+) | PATCH',
    'src/Infrastructure/REST/TournamentsRestController.php | /tournaments/(?P<id>\\d+)/trash | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/blocks | PUT',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/duplicate | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/(?P<id>\\d+)/publish | POST',
    'src/Infrastructure/REST/TrainingPlansRestController.php | /training/plans/generate | POST',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs | POST',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+)/blocks/(?P<block>\\d+) | PATCH',
    'src/Infrastructure/REST/TrainingRunsRestController.php | /training/runs/(?P<id>\\d+)/observations | POST',
    'src/Infrastructure/REST/VisionExtractRestController.php | /vision/extract | POST',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/players/(?P<player_id>\\d+) | PUT',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/share | POST',
    'src/Modules/MatchAnalysis/Rest/MatchAnalysisRestController.php | /activities/(?P<activity_id>\\d+)/analysis/share/rotate | POST',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/\' . $action | ?',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/goal-event/(?P<event_uuid>[a-f0-9-]+)\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/minutes\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/substitution/(?P<event_uuid>[a-f0-9-]+)\' | PATCH',
    'src/Modules/MatchExecution/Rest/MatchExecutionRestController.php | $base . \'/tracked-event\' | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<activity_id>\\d+)/share | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<activity_id>\\d+)/share/rotate | POST',
    'src/Modules/MatchPrep/Rest/MatchPrepRestController.php | /match-prep/(?P<prep_id>\\d+)/role | PUT',
];
