<?php
namespace TT\Modules\CustomCss;

if ( ! defined( 'ABSPATH' ) ) exit;

use TT\Shared\Frontend\BrandFonts;

/**
 * VisualEditor — Path C of the #0064 custom-CSS authoring surface.
 *
 * Maps a structured array of visual settings (colours, fonts, weights,
 * corner radius, spacing scale, shadows) to a generated CSS body that
 * targets the `.tt-root` scoped class. The settings array is what the
 * live preview iframe deserialises and what `CustomCssRepository`
 * persists alongside the live CSS so the operator can re-open Path C
 * without losing their tweaks.
 *
 * Round-trip rule: if the operator saves a Path C settings payload
 * then later edits the CSS body in Path B, the visual_settings field
 * stays alongside as an "imprint" — Path C UI shows a banner ("CSS
 * has been hand-edited; using the visual editor will overwrite it").
 * The decision lives in the view layer; the generator stays
 * deterministic.
 */
final class VisualEditor {

    public const FIELDS = [
        'primary_color',
        'secondary_color',
        'accent_color',
        'danger_color',
        'warning_color',
        'success_color',
        'info_color',
        'focus_ring_color',
        'background_color',
        'surface_color',
        'text_color',
        'muted_color',
        'line_color',
        'font_display',
        'font_body',
        'font_weight_body',
        'font_weight_heading',
        'corner_radius_md',
        'corner_radius_lg',
        'spacing_scale',
        'shadow_strength',
    ];

    /**
     * @param array<string, mixed> $settings
     */
    public static function generateCss( array $settings ): string {
        $tokens = [];
        $palette_to_token = [
            'primary_color'     => '--tt-primary',
            'secondary_color'   => '--tt-secondary',
            'accent_color'      => '--tt-accent',
            'danger_color'      => '--tt-danger',
            'warning_color'     => '--tt-warning',
            'success_color'     => '--tt-success',
            'info_color'        => '--tt-info',
            'focus_ring_color'  => '--tt-focus-ring',
            'background_color'  => '--tt-bg',
            'surface_color'     => '--tt-surface',
            'text_color'        => '--tt-text',
            'muted_color'       => '--tt-muted',
            'line_color'        => '--tt-line',
        ];
        foreach ( $palette_to_token as $field => $token ) {
            $value = self::sanitizeColor( (string) ( $settings[ $field ] ?? '' ) );
            if ( $value !== '' ) $tokens[] = "    {$token}: {$value};";
        }

        $font_display = self::sanitizeFontFamily( (string) ( $settings['font_display'] ?? '' ), BrandFonts::displayCatalogue() );
        if ( $font_display !== '' ) $tokens[] = "    --tt-font-display: {$font_display};";
        $font_body = self::sanitizeFontFamily( (string) ( $settings['font_body'] ?? '' ), BrandFonts::bodyCatalogue() );
        if ( $font_body !== '' ) $tokens[] = "    --tt-font-body: {$font_body};";

        $weight_body = self::sanitizeFontWeight( (string) ( $settings['font_weight_body'] ?? '' ) );
        if ( $weight_body !== '' ) $tokens[] = "    --tt-fw-body: {$weight_body};";
        $weight_heading = self::sanitizeFontWeight( (string) ( $settings['font_weight_heading'] ?? '' ) );
        if ( $weight_heading !== '' ) $tokens[] = "    --tt-fw-heading: {$weight_heading};";

        $r_md = self::sanitizePx( (string) ( $settings['corner_radius_md'] ?? '' ), 0, 32 );
        if ( $r_md !== null ) $tokens[] = "    --tt-r-md: {$r_md}px;";
        $r_lg = self::sanitizePx( (string) ( $settings['corner_radius_lg'] ?? '' ), 0, 40 );
        if ( $r_lg !== null ) $tokens[] = "    --tt-r-lg: {$r_lg}px;";

        $spacing = self::sanitizeFloat( (string) ( $settings['spacing_scale'] ?? '' ), 0.6, 1.6 );
        if ( $spacing !== null ) $tokens[] = "    --tt-spacing-scale: {$spacing};";

        $output = "/* Generated by TalentTrack visual editor (#0064). */\n\n";
        if ( ! empty( $tokens ) ) {
            $output .= ".tt-root {\n" . implode( "\n", $tokens ) . "\n}\n";
        }

        // Optional shadow strength — affects card / panel / tile drop-
        // shadows. `none` removes all box-shadow, `light` keeps the
        // existing soft shadow, `strong` doubles the spread + opacity.
        $shadow = self::sanitizeShadowStrength( (string) ( $settings['shadow_strength'] ?? '' ) );
        if ( $shadow === 'none' ) {
            $output .= "\n.tt-root .tt-panel,\n.tt-root .tt-card,\n.tt-root .tt-mc-card,\n.tt-root .tt-cfg-tile {\n    box-shadow: none;\n}\n";
        } elseif ( $shadow === 'strong' ) {
            $output .= "\n.tt-root .tt-panel,\n.tt-root .tt-card,\n.tt-root .tt-mc-card,\n.tt-root .tt-cfg-tile {\n    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);\n}\n";
        }

        return $output;
    }

    /**
     * Round-trip detection: returns true when `$css_body` looks like
     * it was produced by the generator (so re-opening Path C is safe
     * and won't clobber hand-edited rules).
     */
    public static function isGenerated( string $css_body ): bool {
        return str_contains( $css_body, 'Generated by TalentTrack visual editor (#0064).' );
    }

    public static function sanitizeColor( string $value ): string {
        $value = trim( $value );
        if ( $value === '' ) return '';
        // 3- or 6-digit hex.
        if ( preg_match( '/^#?[0-9a-fA-F]{3}$/', $value ) || preg_match( '/^#?[0-9a-fA-F]{6}$/', $value ) ) {
            return '#' . ltrim( $value, '#' );
        }
        // rgb(a) — minimal validation.
        if ( preg_match( '/^rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*(?:,\s*[\d.]+\s*)?\)$/', $value ) ) {
            return $value;
        }
        return '';
    }

    /**
     * Validate the family against the BrandFonts catalogue and return
     * the CSS-safe family declaration (multi-word names get quoted via
     * `BrandFonts::resolveFamily`). Empty / unknown / sentinel values
     * return ''.
     *
     * @param string[] $catalogue
     */
    public static function sanitizeFontFamily( string $value, array $catalogue ): string {
        return BrandFonts::resolveFamily( trim( $value ), $catalogue );
    }

    public static function sanitizeFontWeight( string $value ): string {
        $value = trim( $value );
        if ( $value === '' ) return '';
        // 100–900 in steps of 100, plus the named weights browsers accept.
        $allowed = [ '100', '200', '300', '400', '500', '600', '700', '800', '900', 'normal', 'bold' ];
        return in_array( $value, $allowed, true ) ? $value : '';
    }

    public static function sanitizePx( string $value, int $min, int $max ): ?int {
        if ( $value === '' ) return null;
        if ( ! preg_match( '/^\d+$/', $value ) ) return null;
        $n = (int) $value;
        if ( $n < $min || $n > $max ) return null;
        return $n;
    }

    public static function sanitizeFloat( string $value, float $min, float $max ): ?float {
        if ( $value === '' ) return null;
        if ( ! is_numeric( $value ) ) return null;
        $n = (float) $value;
        if ( $n < $min || $n > $max ) return null;
        return round( $n, 2 );
    }

    public static function sanitizeShadowStrength( string $value ): string {
        $value = strtolower( trim( $value ) );
        return in_array( $value, [ 'none', 'light', 'strong' ], true ) ? $value : '';
    }
}
